### ISSUE TITLE
TypeError: accept_waitingList() takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by mattcongy** [mattcongy/waitinglist#2]
Error when trying to accept invitation to join the wod. 

Stacktrace : 
`Traceback (most recent call last):
  File "waitinglist.py", line 92, in <module>
    main(sys.argv)
  File "waitinglist.py", line 85, in main
    schedule.run_pending()
  File "/Library/Python/2.7/site-packages/schedule/__init__.py", line 493, in run_pending
    default_scheduler.run_pending()
  File "/Library/Python/2.7/site-packages/schedule/__init__.py", line 78, in run_pending
    self._run_job(job)
  File "/Library/Python/2.7/site-packages/schedule/__init__.py", line 131, in _run_job
    ret = job.run()
  File "/Library/Python/2.7/site-packages/schedule/__init__.py", line 411, in run
    ret = self.job_func()
  File "waitinglist.py", line 61, in start_check
    wodify.accept_waitingList(wmobject)
TypeError: accept_waitingList() takes exactly 2 arguments (1 given)`

**Comment by mattcongy** [comment]
Method signature contains 2 parameters, whereas call from main class is made without `options` parameter passed.

Changed it, need to test with a new waiting list wod.
